# netlify.toml

[build]
  command = "npm run build:clean"
  publish = ".next"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@sparticuz/chromium", "puppeteer-core"]
included_files = [
  "node_modules/@sparticuz/chromium/**"
]

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN_CACHE = "false"
  NETLIFY_USE_NPM_CACHE = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# ðŸ‘‡ Redirige la raÃ­z a tu locale por defecto
[[redirects]]
  from = "/"
  to = "/es"
  status = 308
